### ISSUE TITLE
option to turn off data visualizer

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#10]
For very long protocols, the data visualizer in the protocol creator tool can take up too much memory.  In these cases, we should either simplify the display (to make it take less memory), or provide an option to the user to switch the visualizer off.  Possible also we can have a snapshot mode - so the user has to press a button for the visualizer to update (? if that actually solves the problem, I'm not sure).

In any case, the key is preventing the computer from slowing down on very long, complex protocols.

Received feedback while working with Stefie.

**Comment by SeBassTian23** [comment]
If there are more than 500 pulses, the pulses are not displayed individually, but as a dashed line for the duration of the pulse set
