### ISSUE TITLE
Include protocol JSON in macro editing tool

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#12]
During calibration sequences, it can be useful to know what the intensities and other settings are in the protocol JSON when performing calculations.  One thought is to also give user access to the protocol JSON (the same way we have access to the data JSON) so we can pull out values as needed.

Adding here because I'm wondering if that's a fairly easy thing, given that the data JSON is already there.

**Comment by SeBassTian23** [comment]
We will include that by extending the macro functions as discussed for the next sprint. The data will be available in the macro as the meta data object. I will close this issue as soon as we have the implementation done.

**Comment by SeBassTian23** [comment]
Let's rethink all of this when we talk about the server side processing and the new protocol - macro structure.
