### ISSUE TITLE
exponential regression option in Macro editor

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#13]
I'm working on the LED PAR calibration, and I'm finding that in the available region, the trend is clearly expontential.  It would be useful to have a expontential regression function as well.

**Comment by SeBassTian23** [comment]
I will try to provide that for the macro's. Just want to make sure it is fast enough to process a lot of measurements at the same time.

**Comment by SeBassTian23** [comment]
Added by @bikevin.
