### ISSUE TITLE
after saving, multiple isntances of macros appears in macro dropdown

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#17]
See image below - chlorophyll fluorescence macro appears 3 times in the list, instead of just once as it should (not visible in image below, but if you scroll down in menu you'd see it).

This occured after working with various macros over an hour and performing some edits and saves.

![selection_081](https://cloud.githubusercontent.com/assets/1742369/6012161/c526118c-ab12-11e4-8776-10eba7527eca.png)

**Comment by SeBassTian23** [comment]
Do you have multiple macros in the admin view as well? Or is it restricted to the macro editor? Or restricted to the app?

**Comment by gbathree** [comment]
restricted to macro editor -

Greg

On Tue, Feb 3, 2015 at 12:42 PM, Sebastian <notifications@github.com> wrote:

> Do you have multiple macros in the admin view as well? Or is it restricted
> to the macro editor? Or restricted to the app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/17#issuecomment-72697447>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
fixed
