### ISSUE TITLE
errors which are not passed to the user, macro and protocol saving via chrome app

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#19]
If a macro has a blank protocol JSON or if that JSON does not fulfill the validation requirements, it cannot be saved.  No feedback is given to the user of this failure (only visible in console log as image below).

![selection_082](https://cloud.githubusercontent.com/assets/1742369/6012275/2f1a3f54-ab14-11e4-8763-aba4c7e40266.png)

The following error is given when you try to save an existing macro.  If you sync with database, this allows you to save once before the problem returns.

![selection_083](https://cloud.githubusercontent.com/assets/1742369/6012309/87003976-ab14-11e4-90c5-033a0779b6a2.png)

**Comment by SeBassTian23** [comment]
Should be fixed with the new release and API - please test
