### ISSUE TITLE
script constructor displays 'integrated fluoresce...' protocols incorrectly

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#2]
I think there are a few issues here.  First, in the 'red' version, it doesn't show 14 or 20 at all prior to the measuring pulse, which isn't correct.  In addition, the intensity of the orange actinic light is set to 700, which is not correct (it should be 250)... this may be due to the program confusing the measuring light intensity with the actinic light intensity which is set to 700.

**Comment by SeBassTian23** [comment]
Is this still an issue or do we have this fixed by now?

**Comment by gbathree** [comment]
Yep, it works!
