### ISSUE TITLE
protocol_id converted to 1 when you press "run"

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#25]
We tested this in your office.

**Comment by SeBassTian23** [comment]
Cannot remember what the discussion was. The protocol_ID is empty when a protocol is "Run" from the protocol editor. We need to talk about how macros should be connected for the editor...

**Comment by SeBassTian23** [comment]
Since this didn't come up in a long time and the editor is rewritten, I assume this issue is addressed.
