### ISSUE TITLE
user defined values 10 or >

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#26]
In the nxt firmware version I added more user defined values, but in the calibration info the # wraps from 9 back to zero.  

![selection_237](https://cloud.githubusercontent.com/assets/1742369/6896710/5971b95c-d6bc-11e4-9666-2a703fcec4a4.png)

**Comment by SeBassTian23** [comment]
Should be fixed https://github.com/Photosynq/PhotosynQ-ChromeApp/commit/3c5c60aaf073de89ef8ed825baeff53d4276f729
