### ISSUE TITLE
real-time plotting not working correctly with macros

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#28]
This is an example of the real time out.  It does correctly display some of the macro outputs, but not all.   Below is an example which should show phi2, but does not.  You can also run a macro of the standard phi2 (Chlorophyll fluorescence phi2) with measurement repeats and delays - it does not display all of the macro outputs in the real-time graph.

![real time plotting bug](https://cloud.githubusercontent.com/assets/1742369/6985971/d822c4c4-da06-11e4-946d-025e95fbd4ff.jpg)

**Comment by SeBassTian23** [comment]
Should be fixed now, please test

**Comment by SeBassTian23** [comment]
Ok, the realtime plotting doesn't work for macros if you start the measurement from the protocol editor. I will look into it. This is a general problem and perhaps we need to discuss the workflow here.

**Comment by SeBassTian23** [comment]
Won't the new macro structure prevent realtime plotting?

**Comment by gbathree** [comment]
yes, as it's currently defined I think that's true.  We can still real-time
plot environmentals, but not macro outputs.



On Tue, Nov 24, 2015 at 3:38 PM, Sebastian <notifications@github.com> wrote:

> Won't the new macro structure prevent realtime plotting?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/28#issuecomment-159398318>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
Realtime plotting removed and replaced by sparklines shown when the mouse hovers over the table header.
