### ISSUE TITLE
add links to 'example measurements' when saving a protocol

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#29]
To help users understand what 'typical' protocol should look like.  Link goes to website pages, so we don't have to add lots of images or long strings of numbers.

**Comment by SeBassTian23** [comment]
I'm confused here a bit. Do you want me to make a list of example measurements available for users, which can be picked and added to the description? Do you want a link or do we want to think about a hash tag based system?

**Comment by gbathree** [comment]
I think this came out of our discussions with Dan.  Let's discuss at some
point and make sure we've got it right.  I think the idea was web links to
single data view pages showing typical measurements using that protocol.

On Wed, Apr 15, 2015 at 11:30 AM, Sebastian <notifications@github.com>
wrote:

> I'm confused here a bit. Do you want me to make a list of example
> measurements available for users, which can be picked and added to the
> description? Do you want a link or do we want to think about a hash tag
> based system?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/29#issuecomment-93449864>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
Let's move this to the API, so that we can upload images, or we do it from the website. Either case we need an API to reflect these changes
