### ISSUE TITLE
add ability to change auto-shutoff time with firmware 0.39

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#30]
Call on 1033+. Sets how long it takes to power off the device (in ms).  If set to 0 - 5000 will default to 12000 (2 minutes), if set to < 0 will default to 9999999999 (way long time).

**Comment by SeBassTian23** [comment]
The function is implemented in v0.28. I hope it works. Please confirm.

**Comment by gbathree** [comment]
Yes - in firmware 0.40 function works - have used it and it works great!

On Wed, Apr 15, 2015 at 11:18 AM, Sebastian <notifications@github.com>
wrote:

> The function is implemented in v0.28. I hope it works. Please confirm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/30#issuecomment-93445004>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org
