### ISSUE TITLE
Jpegs do not display in "Overview"

### ISSUE THREAD

**Issue by Fastie** [Photosynq/PhotosynQ-ChromeApp#32]
In this project (http://www.photosynq.org/projects/289) two jpeg images in the Overview section fail to display in the Chrome app. These jpegs display in the web app, but not in the Android App.
Windows 7, Chrome 42.0.2...

**Comment by SeBassTian23** [comment]
Right now, we are working on getting this issue addressed within the next few weeks. The chrome app  is not displaying those images, since it is simply not implemented. It is a violation of the content security policy, to be technical. I hope it is not affecting your current workflow too much!

**Comment by gbathree** [comment]
Chris - we're actually moving to markdown with images separated from text.
I'm *hoping* that this addresses a lot of the issues with the WYSIWYG which
I hate.  Also, it'll make everything easier to transfer via API as images
and text will be separated and you won't have messy HTML tags all over the
place, so it's easier for things like the Chrome app to organize the images
and text effectively.

Greg

On Mon, Apr 27, 2015 at 11:19 AM, Sebastian <notifications@github.com>
wrote:

> Right now, we are working on getting this issue addressed within the next
> few weeks. The chrome app is not displaying those images, since it is
> simply not implemented. It is a violation of the content security policy,
> to be technical. I hope it is not affecting your current workflow too much!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/32#issuecomment-96701116>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
To this point the API is not delivering any images, other than the general one, and if images get included in the description, they get deleted in the chrome app, since there is no secure way of grabbing them. This will be fixed by the API some time in the future.
