### ISSUE TITLE
Open spectrophotometer has a new window

### ISSUE THREAD

**Issue by teravestdan** [Photosynq/PhotosynQ-ChromeApp#33]
If the spectrophotometer comes up as a pop-up window, then all the data can be lost if the user clicks on a shaded part of the screen. Would be better to have the spectrophotometer open has a new window, similar to the protocol builder.

**Comment by SeBassTian23** [comment]
Thanks for pointing that out. I have fixed that issue. Now you have to close the dialog by hitting the esc button or click on the x in the upper right corner.
