### ISSUE TITLE
Spectrophotometer intensities need to be based on cuvette holder

### ISSUE THREAD

**Issue by teravestdan** [Photosynq/PhotosynQ-ChromeApp#35]
The light intensities on the spectophotometer appear to be based on a clamped device without a cuvette holder. When a cuvette holder is in place, the error is quite large.

**Comment by SeBassTian23** [comment]
I'm not sure if something is implemented now, or if we still need to improve this. Let's talk and see if it is still needed, or if we just bump it up to the next version of the device.

**Comment by gbathree** [comment]
agreed

On Tue, Nov 24, 2015 at 3:43 PM, Sebastian <notifications@github.com> wrote:

> I'm not sure if something is implemented now, or if we still need to
> improve this. Let's talk and see if it is still needed, or if we just bump
> it up to the next version of the device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/35#issuecomment-159399476>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
Since there is no cuvette holder for the new MultispeQ version, let's see what we are going to do with the spectrophotometer mode. Perhaps we shouldn't even support it, unless we think it is a useful tool.

**Comment by gbathree** [comment]
The new cuveette will have a cuvette holder - let's make sure that we work
on that once we have a working device.  I don't think we need a lot of work
to make a reasonable solution - it's been designed to be cuvette ready.

On Fri, Mar 4, 2016 at 11:11 PM, Sebastian <notifications@github.com> wrote:

> Closed #35 <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/35>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/35#event-578446283>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org
