### ISSUE TITLE
problems with y-axis scaling

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#36]
Still has scaling issues on y axis -

![selection_302](https://cloud.githubusercontent.com/assets/1742369/7383549/6c022cd8-edef-11e4-97fd-936fbcf2bd65.png)

![selection_303](https://cloud.githubusercontent.com/assets/1742369/7383562/af274d7c-edef-11e4-81cd-5945aeebda55.png)

**Comment by SeBassTian23** [comment]
I know... it is easy to add more decimal points. The issue is to adjust the axis label margins. When I figure a good solution, I will change it.

**Comment by SeBassTian23** [comment]
OK, this issue should be addressed... https://github.com/Photosynq/PhotosynQ-ChromeApp/commit/4733c00afb6ec795d50904a36adfcc349747e5b8
Please test master branch
