### ISSUE TITLE
Data explorer not showing The One or SPAD data

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#38]
When exploring the data in this project, the current data explorer does not show any of the outputs from SPAD or The One.  Do you know what the issue is?

http://www.photosynq.org/projects/manufacturing-final-testing/explore_data

This may be resolved in the new version of the data explorer

**Comment by SeBassTian23** [comment]
Hm, the macro gets applied and the data is in there. I have to double-check
what happens there. I hope this is resolved with the new version.

On Thu, May 14, 2015 at 10:32 AM, gbathree <notifications@github.com> wrote:

> When exploring the data in this project, the current data explorer does
> not show any of the outputs from SPAD or The One. Do you know what the
> issue is?
>
> http://www.photosynq.org/projects/manufacturing-final-testing/explore_data
>
> This may be resolved in the new version of the data explorer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/38>.
>



-- 
Sebastian Kuhlgert
1330 Westview Ave. Apt. 192B
48823 East Lansing, Mi
USA
+1 (517) 303-1413

**Comment by gbathree** [comment]
@SeBassTian23 can you check this particular dataset in the new data explorer to see if it works?  This is another good test case which currently fails.

http://www.photosynq.org/projects/manufacturing-final-testing/explore_data
