### ISSUE TITLE
Improved firmware update process

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#39]
Here's the new directions for firmware updates (same cross platform).  If there's any way to hand hold users through the process after they click to update firmware (with popups going 'next', 'next'... etc.) that'd be good.  

Go to "Device" and click “check” to see if you have the newest firmware version.  When new firmware versions are available this will indicate there is one available for download.  If so, click and download the .hex file.  Then go download Arduino 1.6.3 (NOT the newest version!) here: http://www.arduino.cc/en/Main/OldSoftwareReleases#previous (in Windows right click on installation file and click “run as Administrator”).  First, go to https://www.pjrc.com/teensy/td_download.html and follow instructions for installing the teensyduino for your operating system (again, in Windows right click on installation file and click “run as Administrator”).

In Linux, you can open teensyduino by finding the Arduino install folder and going to → hardware → tools and clicking on Teensy.  In a Mac, you go to Applications, right click on Arduino and Show Package Contents, then go to content → resources → java → hardware → tools.  In Windows, go to c:/Program Files (x86) → Arduino → hardware → tools.  Follow these directions exactly:

Open PhotosynQ Chrome App, and connect to your device.  
Open Teensyduino.
In Chrome app, click on Device → Reboot.
In Teensyduino, load the .hex file you downloaded
In Teensyduino, click the “Program” button, then the “Reboot” button
Disconnect the device completely, and wait 5 seconds, then reconnect
In Chrome app, refresh the connection and connect.
Now go to Devices and check the firmware version.  It should be updated!

**Comment by SeBassTian23** [comment]
Let's rethink this with the possible over the air update...

**Comment by gbathree** [comment]
agreed this will be addressed other ways -
