### ISSUE TITLE
Canceling Measurements makes the UI wait for the device

### ISSUE THREAD

**Issue by SeBassTian23** [Photosynq/PhotosynQ-ChromeApp#41]
If a measurement gets canceled, the application is waiting for the device to end the measurement. This might lead to long wait times. It can be overcome, by disconnecting the device.

At this point the issue is due to the way the firmware handles a cancel. Let's see how we can address that issue!?

**Comment by gbathree** [comment]
This should be addressed with new cancel button

**Comment by SeBassTian23** [comment]
Right now `-1+-1+` is send to cancel a measurement. Is this issue addressed?

**Comment by SeBassTian23** [comment]
Fix will be in the next release.
