### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by SeBassTian23** [Photosynq/PhotosynQ-ChromeApp#48]
Update the documentation to help the user with the firmware update process.

**Comment by SeBassTian23** [comment]
What are the minimum requirements for a over the air firmware update, @gbathree?

**Comment by gbathree** [comment]
Everything will have over the air firmware updates enabled.  We'll make
sure to update all old devices (beta and v1.0) so firmware is compatible.

Greg

On Wed, Feb 10, 2016 at 2:57 PM, Sebastian <notifications@github.com> wrote:

> What are the minimum requirements for a over the air firmware update,
> @gbathree <https://github.com/gbathree>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/48#issuecomment-182552925>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
How do we ensure, that we deliver the right firmware to the right device? Or do we have a global for both?

**Comment by gbathree** [comment]
t
​wo options - (1) we can ask the device if it's beta or 1.0 and send it the
right firmware (hardcode the sources at this point), or (2) we can just not
include over the air for beta.  ​I don't think I can have a global from a
firmware perspective, that'll get really tricky.  We need to check the
device info regardless before updating, so I think (??) option 1 isn't too
much additional work (??) , especially if things are hardcoded for the
moment anyway.

On Wed, Feb 10, 2016 at 5:55 PM, Sebastian <notifications@github.com> wrote:

> How do we ensure, that we deliver the right firmware to the right device?
> Or do we have a global for both?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/48#issuecomment-182619895>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
Major update for the help documentation is now released. Needs some polishing, but I think it is a good template for now.
