### ISSUE TITLE
bug when there is a measurement error

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#51]
I was testing some firmware which caused the data json returned to the app to be invalid.  I had the 'output' mode on so I could see the raw text.  Chrome app successfully alerted me to the invalid JSON, but I was then unable to click to any other menus - it was stuck with 'cancel', 'skip wait', and 'output' at the top bar.  I couldn't even go to projects or other menus.

When I clicked on 'controls' and 'co2' the menus reset and I was able to work again.

**Comment by SeBassTian23** [comment]
Bug should be fixed https://github.com/Photosynq/PhotosynQ-ChromeApp/commit/76a92a6393162648774b89efbaff87247b10a8d5
