### ISSUE TITLE
duplicated macro names in new app

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#70]
So I had the create new macro screen open, and was saving it.  At the same time, I had the save protocol screen open (this allowed me to copy the name and info from the protocol into the macro).  I saved the macro, close the saved protocol screen, and attempted to select my newly saved macro from the dropdown as seen in the image.  But it now produced duplicates of all of the macros in the dropdown. 

Minor bug but I thought I'd at least note it here.

![selection_616](https://cloud.githubusercontent.com/assets/1742369/14230415/da132fde-f923-11e5-9b8a-c2e27186b206.png)

**Comment by SeBassTian23** [comment]
Issue was due to the MacroList function being called twice asynchronously. Everything got put into one function call. Same was implemented for protocols, just to be sure and reduce the calls to the internal database.
Fixed c77184df2fb3746536559fcefc1768106b0d4699
