### ISSUE TITLE
items in my protocols and explore list disappear

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#71]
if you enter something in the "search Protocols" bar, the protocols are auto-filtered.  Now leave protocols into macros or protocol editor, and then come back to the Protocols screen.  In my experience, the screen is now blank.  Even when you delete the contents of the search bar at this point, no protocols show back up.  I must restart to fix the problem.  

![selection_626](https://cloud.githubusercontent.com/assets/1742369/14333304/06513230-fc1c-11e5-9088-5d1980301e49.png)

**Comment by SeBassTian23** [comment]
Hm, seems to be specific to your system. I cannot replicate the issue. Can you add the console output as well?

Thanks

--
Sebastian Kuhlgert
1330 Westview Ave. Apt. 192B
48823 East Lansing, Mi
USA
+1 (517) 303-1413

**Comment by SeBassTian23** [comment]
Should be addressed https://github.com/Photosynq/PhotosynQ-ChromeApp/commit/d50fd86a611f114bf4f2c96e33af121fc6323d08.
