### ISSUE TITLE
add warning, info, danger

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#73]
This has been added on the android app, just want it also on the chrome app to be consistent.  Danger is red, Warning is yellow, and info is white.  

Currently, the quality messages are not viewable because they are returned as an array, which simply contacts "objects" - see screenshot below.

![selection_671](https://cloud.githubusercontent.com/assets/1742369/14875270/10b8bf9c-0cd7-11e6-88ad-7d6bfb2caa94.png)

**Comment by SeBassTian23** [comment]
Sure, let me know how you want it implemented. Since the table can have multiple rows with different measurements, some good some bad we need a consistent way of showing it, without using a lot of space. I would suggest coloring the row, showing and adding a pop up with the message on hover. What do you think?

**Comment by gbathree** [comment]
Yep, pretty much, though I just want to make sure those warning items are
prioritized in terms of location on the page (so they don't get buried).
Let's talk Monday and nail down a design.


On Thu, Apr 28, 2016 at 10:19 AM, Sebastian <notifications@github.com>
wrote:

> Sure, let me know how you want it implemented. Since the table can have
> multiple rows with different measurements, some good some bad we need a
> consistent way of showing it, without using a lot of space. I would suggest
> coloring the row, showing and adding a pop up with the message on hover.
> What do you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-ChromeApp/issues/73#issuecomment-215439702>
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by SeBassTian23** [comment]
Feature added, just requires some more testing 42f3bb19fc55d2ab11f0c8dd1a90c8909c66522f
