### ISSUE TITLE
light on pin 11,12,15,16,10,14 in protocol creator doesn't display correctly when set to non-pulsed

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#8]
If you set pin 11,12,15,16,10,14 as a non-pulsed light, and set intensity for lights 11,12,15,16 and intensity for 10,14 at some high value (say 4000), the pin does not display at that intensity in the light visualizer.

**Comment by SeBassTian23** [comment]
Is this still an issue or is it solved with the latest updates?

**Comment by gbathree** [comment]
Yep looks good now!
