### ISSUE TITLE
Chrome App Migration?

### ISSUE THREAD

**Issue by bgiesing** [Photosynq/PhotosynQ-ChromeApp#81]
In case you haven't seen yet @SeBassTian23, Google is discontinuing Chrome apps on every platform except Chrome OS. Any plans for this? Google says devs should convert it to either Progressive Web Apps or native packaging with Electron/NW.js.

https://developers.chrome.com/apps/migration

**Comment by SeBassTian23** [comment]
I'm currently exploring the migration to Electron. Seems the only feature missing is a gcm api, which we currently use for syncing. So we would have to implement a different solution.

Thanks for the update!

**Comment by SeBassTian23** [comment]
We will use the Electron framework to migrate the app. A first early version looks promising, yet the GCM issue still needs to be addressed.
