### ISSUE TITLE
double row number after add row before row 5

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#83]
Another little bug - notice row 5.  When I added a row after row 5 (copying row 5), it produced 2 row fives.  

Also, when I switch to advanced and then back in, the 2nd added row 5 is gone - completely.  So instead of being 24 rows, there is only 23!  I could add the data only by going into advanced and manually adding the information.

![selection_967](https://cloud.githubusercontent.com/assets/1742369/18289157/3b97417a-744c-11e6-8adc-eca3358eb916.png)

**Comment by bikevin** [comment]
fixed on development branch
