### ISSUE TITLE
fixed versus table variables

### ISSUE THREAD

**Issue by gbathree** [Photosynq/PhotosynQ-ChromeApp#84]
imagine you have:

```
[
	{
		"pulses": [
			24
		],
		"pulse_distance": [
			200000
		],
		"pulse_length": [
			2
		],
		"pulsed_lights": [
			10
		],
		"environmental": [
			[
				"digital_write",
				14,
				1
			]
		]
	}
]
```

and you add

```
		"environmental_array": [
			[
				"light_intensity"
			]
		]
```

to it either in table view or advanced.  If you then enter advanced and return to table view, the "environmental_array" gets sucked up into the table listing (out of fixed).  

Is it possible to check the wiki page to see if it's table or fixed and place it based on that information rather than (or perhaps in addition to) matching the number of elements in the array?  This can cause a lot of confusion (it has for me a few times).

**Comment by bikevin** [comment]
fixed with commit 2e036f99b20ffa1f2b68eb5635e6378e33f5b958
