### ISSUE TITLE
connecting macro's to protocols

### ISSUE THREAD

**Issue by teravestdan** [Photosynq/PhotosynQ-ChromeApp#85]
It is very difficult to scroll thru the list of macro's in the chrome app to find the proper macro to associate to a protocol. Also, the macro's are repeated within the dropdown menu. Is it possible to start typing in the name of the macro and have it autofill/suggest? Or another method of making it easier to find the macro?

**Comment by SeBassTian23** [comment]
I will add it to the list of implementations in the new version of the app.
